version: '3.9'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    expose:
        - "27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
  web:
    image: frontend-image:latest
    ports:
      - "8082:80"
  server:
    image: server-image:latest
    ports:
      - "5000:5000"
    links:
      - mongodb
 
  